VGCodeDJCitasMedicas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from citasmedicas import views
from rest_framework import routers, serializers, viewsets
from rest_framework.urlpatterns import format_suffix_patterns


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^citasmedicas/', include('citasmedicas.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^', include(router.urls)),
]

citasmedicas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
urlpatterns = [
    url(r'^$', views.citasmedicas_index, name='citasmedicas_index'),
    url(r'^login$', views.login_page, name='login'),
    url(r'^logout$', views.logout_page, name='logout'),
    url(r'^secretaria/alta$', views.secretaria_alta, name='secretaria_alta'),
    url(r'^secretaria/lista$', views.secretaria_lista,
        name='secretaria_lista'),
    url(r'^secretaria/edita/(?P<pk>\d+)$', views.secretaria_edita,
        name='secretaria_edita'),
    url(r'^paciente/alta/$', views.paciente_alta, name='paciente_alta'),
    url(r'^paciente/lista/$', views.paciente_lista, name='paciente_lista'),
    url(r'^paciente/editar/(?P<pk>\d+)/$', views.paciente_editar,
        name='paciente_editar'),
    url(r'^consultorio/alta/$', views.consultorio_alta,
        name='consultorio_alta'),
    url(r'^consultorio/lista/$', views.consultorio_lista,
        name='consultorio_lista'),
    url(r'^consultorio/editar/(?P<pk>\d+)/$', views.consultorio_editar,
        name='consultorio_editar'),
    url(r'^doctores/$', views.ListaDoctores.as_view()),
    url(r'^doctores/(?P<pk>[0-9]+)/$', views.DetalleDoctores.as_view()),
    url(r'^listadoctores/$', views.lista_doctores_api, name='listadoctores'),
]

urlpatterns = format_suffix_patterns(urlpatterns, suffix_required=False,
                                     allowed=None)

citasmedicas/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Doctor(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE,
                                related_name='doctor')
    nombres = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=50)
    apellido_materno = models.CharField(max_length=50, blank=True)
    titulo = models.CharField(max_length=100)
    especialidad = models.CharField(max_length=50, blank=True, null=True)
    cedula_profesional = models.CharField(max_length=8)
    cedula_especialidad = models.CharField(max_length=8)
    registro_ssa = models.CharField(max_length=8)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField("Activo", default=True)

    class Meta(object):
        verbose_name_plural = 'Doctores'

    def __str__(self):
        return self.nombres


class Secretaria(models.Model):
    doctor = models.ForeignKey(Doctor, related_name='secretaria')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nombres = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=50)
    apellido_materno = models.CharField(max_length=50, blank=True)
    telefono_personal = models.IntegerField(blank=True, null=True)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField("Activo", default=True)

    def __str__(self):
        return self.nombres


class Paciente(models.Model):
    doctor = models.ForeignKey(Doctor, related_name='pacientes')
    paciente = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=150)
    email = models.EmailField(null=True, blank=True)
    apellido_paterno = models.CharField(max_length=150)
    apellido_materno = models.CharField(max_length=150)
    telefono_personal = models.IntegerField()
    fecha_nacimiento = models.DateField()
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField("Activo", default=True)

    def __str__(self):
        return self.nombre


class CatalogoEstados(models.Model):
    estado = models.CharField('Estado', max_length=100)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField("Activo", default=True)

    class Meta(object):
        verbose_name_plural = 'Catalogo Estados'

    def __unicode__(self):
        return self.estado


class CatalogoMunicipio(models.Model):
    municipio = models.CharField('Municipio', max_length=100)
    estado = models.ForeignKey(CatalogoEstados)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField("Activo", default=True)

    class Meta(object):
        verbose_name_plural = 'Catalogo Municipio'

    def __unicode__(self):
        return self.municipio


class Consultorio(models.Model):
    doctor = models.ForeignKey(Doctor)
    nombre = models.CharField('Nombre del consultorio', max_length=50)
    estado = models.ForeignKey(CatalogoEstados)
    municipio = models.ForeignKey(CatalogoMunicipio)
    colonia = models.CharField('Colonia', max_length=100)
    calle = models.CharField('Calle', max_length=100)
    cruce_a = models.CharField('Cruce A', max_length=100)
    cruce_b = models.CharField('Cruce B', max_length=100)
    numero_exterior = models.CharField('Numero exterior', max_length=100)
    numero_interior = models.CharField('Numero interior', max_length=100)
    telefono = models.CharField('Telefono', max_length=11)
    ext = models.CharField('Extencion', max_length=11)
    latitude = models.CharField(max_length=50)
    longitude = models.CharField(max_length=50)
    descripcion = models.TextField("Extras")
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField("Activo", default=True)

    def __str__(self):
        return self.nombre


class Horario(models.Model):
    consultorio = models.ForeignKey(Consultorio)
    DIA_DOMINGO = 'DO'
    DIA_LUNES = 'LU'
    DIA_MARTES = 'MA'
    DIA_MIERCOLES = 'MI'
    DIA_JUEVES = 'JU'
    DIA_VIERNES = 'VI'
    DIA_SABADO = 'SA'
    DIA_SEMANA_CHOICES = (
        (DIA_DOMINGO, 'Domingo'),
        (DIA_LUNES, 'Lunes'),
        (DIA_MARTES, 'Martes'),
        (DIA_MIERCOLES, 'Miercoles'),
        (DIA_JUEVES, 'Jueves'),
        (DIA_VIERNES, 'Viernes'),
        (DIA_SABADO, 'Sabado'),
    )
    dia_semana = models.CharField(
        max_length=2,
        choices=DIA_SEMANA_CHOICES,
        default=DIA_LUNES,
    )
    hora_inicio = models.TimeField()
    hara_fin = models.TimeField()

    def __str__(self):
        return self.dia_semana


class Cita(models.Model):
    consultorio = models.ForeignKey(Consultorio)
    paciente = models.ForeignKey(Paciente)
    fecha = models.DateField()
    hora = models.TimeField()
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField("Activo", default=True)


class Receta(models.Model):
    consultorio = models.ForeignKey(Consultorio)
    paciente = models.ForeignKey(Paciente)
    fecha = models.DateField()
    hora = models.TimeField()
    diagnostico = models.TextField()
    tratamiento = models.TextField()
    talla = models.CharField(max_length=20)
    peso = models.CharField(max_length=20)
    edad = models.CharField(max_length=20)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField("Activo", default=True)

citasmedicas/forms.py
# coding: utf-8
from django import forms
from citasmedicas.models import Secretaria, Paciente, Consultorio, Doctor
from django.contrib.auth.models import User
from django.contrib.admin.widgets import AdminDateWidget
from datetime import datetime


class LoginForm(forms.Form):
    usuario = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Usuario'}))
    contrasena = forms.CharField(label='Contraseña',
                                 widget=forms.PasswordInput(
                                     attrs={'class': 'form-control',
                                            'placeholder': 'Contraseña'}))


class SecretariaForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'email'}))
    contrasena = forms.CharField(label='Contraseña',
                                 widget=forms.PasswordInput(
                                     attrs={'class': 'form-control',
                                            'placeholder': 'Contraseña'}))
    repite_contrasena = forms.CharField(label='Repite contraseña',
                                        widget=forms.PasswordInput(
                                            attrs={'class': 'form-control',
                                                   'placeholder':
                                                   'Contraseña'}))

    class Meta:
        model = Secretaria
        fields = ('nombres', 'apellido_paterno',
                  'apellido_materno', 'telefono_personal')
        labels = {
            'telefono_personal': 'Teléfono personal'
        }
        widgets = {
            'nombres': forms.TextInput(attrs={'class': 'form-control',
                                              'placeholder': 'Nombres'}),
            'apellido_paterno': forms.TextInput(
                attrs={'class':
                       'form-control', 'placeholder': 'Apellido paterno'}),
            'apellido_materno': forms.TextInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Apellido materno'}),
            'telefono_personal': forms.NumberInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Teléfono personal',
                       'max': '9999999999'})
        }

    def clean_usuario(self):
        datos_limpios = self.cleaned_data
        usuario = datos_limpios.get('usuario')
        if User.objects.filter(username=usuario).exists():
            raise forms.ValidationError(
                "El usuario '%s' ya existe. Capture uno nuevo." % usuario)
        return usuario

    def clean_repite_contrasena(self):
        datos_limpios = self.cleaned_data
        contrasena = datos_limpios.get('contrasena')
        repite_contrasena = datos_limpios.get('repite_contrasena')
        if contrasena != repite_contrasena:
            raise forms.ValidationError(
                "La contraseña no es igual, intente de nuevo.")
        return repite_contrasena


class SecretariaEditForm(forms.ModelForm):

    class Meta:
        model = Secretaria
        fields = ('nombres', 'apellido_paterno',
                  'apellido_materno', 'telefono_personal')
        labels = {
            'telefono_personal': 'Teléfono personal'
        }
        widgets = {
            'nombres': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Nombres'}),
            'apellido_paterno': forms.TextInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Apellido paterno'}),
            'apellido_materno': forms.TextInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Apellido materno'}),
            'telefono_personal': forms.NumberInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Teléfono personal',
                       'max': '9999999999'})
        }


class PacienteForm(forms.ModelForm):
    nombre = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Nombre'})
    )
    apellido_paterno = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Apellido paterno'})
    )
    apellido_materno = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Apellido materno'})
    )
    telefono_personal = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Teléfono personal',
               'max': '9999999999'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=False
    )
    fecha_nacimiento = forms.DateField(widget=forms.SelectDateWidget(
        years=range(1980, datetime.now().year + 1)
    ))

    class Meta:
        model = Paciente
        fields = ('nombre', 'apellido_paterno',
                  'apellido_materno', 'telefono_personal',
                  'fecha_nacimiento')


class ConsultorioForm(forms.ModelForm):
    nombre = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Nombre del consultorio'}
    ))
    colonia = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Colonia'}))
    calle = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Calle'}))
    cruce_a = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Cruce'}))
    cruce_b = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Cruce'}),
                              required=False)
    numero_exterior = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Exterior'}))
    numero_interior = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'interior'}),
                                      required=False)
    telefono = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Telefono'}))
    ext = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Extencion'}),
                          required=False)
    latitude = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'readonly': 'readonly',
                                      })
    )
    longitude = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'readonly': 'readonly',
                                      })
    )

    descripcion = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = Consultorio
        fields = ('nombre', 'estado', 'municipio', 'colonia', 'calle',
                  'cruce_a', 'cruce_b', 'numero_exterior', 'numero_interior',
                  'telefono', 'ext', 'latitude', 'longitude', 'descripcion')

        widgets = {
            'estado': forms.Select(
                attrs={'class': 'form-control'}),
            'municipio': forms.Select(
                attrs={'class': 'form-control'}),
        }

citasmedicas/templates/citasmedicas/_messages.html
{% if messages %}
    <div class="row dj-messages">
    <div class="col-md-6 col-md-offset-3">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
            {% else %}
                <div class="alert alert-{{ message.tags }}" role="alert">
            {% endif %}
            <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        {% endfor %}
        </div>
        {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
    </div>
{% endif %}

citasmedicas/templates/citasmedicas/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Citas medicas</title>
    <link href="{% static 'citasmedicas/bootstrap-3.3.7/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'citasmedicas/bootstrap-3.3.7/css/bootstrap-theme.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'citasmedicas/css/vgcode.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'citasmedicas/js/jquery-3.1.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.16/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.4"></script>
    <script src="{% static 'citasmedicas/js/vgcode.js' %}"></script>
    <script src="{% static 'citasmedicas/js/main.js' %}"></script>
    <script src="{% static 'citasmedicas/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBOmdwL1LUyF3uBW6rpw81iW32y1FYSf4Y&callback=myMap"></script>
</head>
<body>
<div class="container">
    {% if user.is_authenticated %}
        <nav class="navbar" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Citas medicas</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'citasmedicas_index' %}">Citas</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Paciente<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'paciente_alta' %}">Alta</a></li>
                            <li><a href="{% url 'paciente_lista' %}">Modificación</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Secretaria<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'secretaria_alta' %}">Alta</a></li>
                            <li><a href="{% url 'secretaria_lista' %}">Modificación</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Consultorio<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'consultorio_alta' %}">Alta</a></li>
                            <li><a href="{% url 'consultorio_lista' %}">Modificación</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span> Bienvenido: {{ user.username }}</a></li>
                    <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Salir</a></li>
                </ul>
            </div>
        </nav>
    {% endif %}
</div>
<div class="starter-template"   >
    {% include 'citasmedicas/_messages.html' %}
    {% block content %}{% endblock content %}
</div>
<div class="container">
  <nav class="navbar navbar-inverse  navbar-fixed-bottom" id="footer">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                </button>
                <a class="navbar-brand" href="#">&copy; 2017 VG-Code</a>
                <a class="navbar-brand" href="#"></a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">

                </ul>
                <ul class="nav navbar-nav navbar-right">

                </ul>
            </div><!--/.nav-colapse -->
        </div>
    </nav>
</div>
</body>
</html>

citasmedicas/templates/citasmedicas/citasmedicas_index.html
{% extends "citasmedicas/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <h1 style="font-size:63px;text-align:center;">Aqui ira la pantalla principal</h1>
    </div>
</div>
{% endblock %}

citasmedicas/templates/citasmedicas/login.html
{% extends "citasmedicas/base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row center-block" style="width:300px">
        <img class="img-responsive center-block" src="{% static 'citasmedicas/img/doctor_login.png' %}">
        <h1 class="text-center">Iniciar sesión</h1>
        {% if mensaje %}
            <div class="alert alert-warning text-center">{{mensaje}}</div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
            <fieldset class="control-group">
                <label class="control-label" for="id_{{field.name}}">{{field.label}}</label>
                <div class="controls">
                    <div class="input-group input-group-lg">
                        <span class="input-group-addon">
                            <span class="glyphicon {% if field.name == 'usuario' %}glyphicon-user{% else %}glyphicon-lock{% endif %}"></span>
                        </span>
                        {{field}}
                        <p class="help-text">{{field.help_text}} </p>
                    </div>
                </div>
            </fieldset>
            {% endfor %}
            <br>
            <input class="form-control btn btn-primary" type="submit" value="Entrar" />
        </form>
    </div>
</div>
{% endblock %}

citasmedicas/templates/citasmedicas/paciente_alta.html
{% extends "citasmedicas/base.html" %}
{% include 'citasmedicas/_messages.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div id="menu-options" class="col-lg-2 col-md-2 col-sm-3 col-xs-20">
        {% if form %}
        <div class="container">
          <div class="col-lg-3 col-md-10 col-sm-9 col-xs-14 panel-product">
            <div class="panel-body text-center">
              <h1>Paciente</h1>
              <p>Ingresar datos del paciente</p>
              <button class="btn" type="button" onclick="goBack()">Regresar</button>
            </div>
          </div>
          <div class="col-lg-7 col-md-10 col-sm-9 col-xs-14 panel-product">
            <div class="panel panel-default panel-menu panel-body">
              <form method="POST" class="form">
                  {% csrf_token %}
                  <div class="form-group col-md-12">
                    <label>Nombre</label>
                    {{ form.nombre }}
                  </div>
                  <div class="form-group col-md-6">
                    <label>Apellido Paterno</label>
                    {{ form.apellido_paterno }}
                  </div>
                  <div class="form-group col-md-6">
                    <label>Apellido Materno</label>
                    {{ form.apellido_materno }}
                  </div>
                  <div class="form-group col-md-12">
                    <label>Correo</label>
                    {{ form.email }}
                  </div>
                  <div class="form-group col-md-12">
                    <label for="id_telefono_personal">Telefono Personal</label>
                    {{ form.telefono_personal }}
                  </div>
                  <div class="form-group col-md-12">
                    <span>Fecha de nacimiento:</span>
                    {{ form.fecha_nacimiento }}
                  </div>
                  <div class="form-group col-lg-12">
                    <center>                      
                      <button class="form-control btn btn-primary" type="submit">
                        <i class="glyphicon glyphicon-edit"> Guardar </i>
                      </button>
                      <button class="form-control btn btn-warning" type="reset">
                        <i class="glyphicon glyphicon-remove"> Cancelar </i>
                      </button>
                    </center>
                  </div>
              </form>
            </div>
            <hr>
          </div>
        </div>
        {% endif %}
        {% if form_edit %}
        <div class="container">
          <div class="col-lg-3 col-md-10 col-sm-9 col-xs-14 panel-product">
            <div class="panel-body text-center">
              <h1>Paciente</h1>
              <p>Editar datos del paciente</p>
              <button class="btn" type="button" onclick="goBack()">Regresar</button>
            </div>
          </div>
          <div class="col-lg-7 col-md-10 col-sm-9 col-xs-14 panel-product">
            <div class="panel panel-default panel-menu panel-body">
              <form method="POST">
                  {% csrf_token %}
                  <div class="form-group col-md-12">
                    <label>Nombre</label>
                    {{ form_edit.nombre }}
                  </div>
                  <div class="form-group col-md-6">
                    <label>Apellido Paterno</label>
                    {{ form_edit.apellido_paterno }}
                  </div>
                  <div class="form-group col-md-6">
                    <label>Apellido Materno</label>
                    {{ form_edit.apellido_materno }}
                  </div>
                  <div class="form-group col-md-12">
                    <label>Telefono Personal</label>
                    {{ form_edit.telefono_personal }}
                  </div>
                  <div class="form-group col-md-12">
                    <span>Fecha de nacimiento:</span>
                    {{ form_edit.fecha_nacimiento }}
                  </div>
                  <div class="form-group">
                    <center>
                      <button class="form-control btn btn-primary" type="submit">Editar</button>
                    </center>
                  </div>
              </form>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
    {% if results.pacientes %}
      <div class="container" id="seach_data">
        <div class="row">
          <div id="menu-options" class="col-xs-20">
              <div class="page-header"><h2>Búsquedas</h2></div>
              <form action="." method="GET" role="form">
                  {% csrf_token %}
                  <div class="form-group">
                      <div class="input-group col-md-12">
                          <input type="text" name="q" value="{{ query|escape }}"  class="form-control" placeholder="Buscar" />
                          <span class="input-group-btn">
                              <button  class="btn btn-info" type="submit">
                                  <i class="glyphicon glyphicon-search"></i>
                              </button>
                              <a href="{% url 'paciente_alta' %}" class="btn btn-success">
                                Agregar Paciente
                                <i class="glyphicon glyphicon-plus"></i>
                              </a>
                          </span>
                      </div>
                  </div>
              </form>
              {% if query %}
                  <div class="panel panel-success">
                      <div class="panel-heading">
                          <span class="glyphicon glyphicon-hdd"></span>
                      </div>
                      <div class="panel-body">
                              <h4>Resultados para "{{ query|escape }}":</h4>
                      </div>
                  </div>
              {% endif %}
          </div>
        </div>
      </div>
      <div class="panel panel-success">
          <div class="panel-heading">Pacientes agregados</div>
          <div class="panel-body">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Apellidos</th>
                  <th>Fecha de nacimiento</th>
                  <th>Doctor</th>
                  <th>Editar</th>
                </tr>
              </thead>
              <tbody>
                {% for paciente in results.pacientes %}
                  <tr>
                    <td>{{paciente.nombre}}</td>
                    <td>{{paciente.apellido_paterno}} {{paciente.apellido_materno}}</td>
                    <td>{{paciente.fecha_nacimiento}}</td>
                    <td>{{paciente.doctor}}</td>
                    <td><a href="{% url 'paciente_editar' pk=paciente.pk %}" class="list-group-item"><span class="glyphicon glyphicon-edit"></span></a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
      </div>
    {% else %}
      {% if query %}
        <div class="alert alert-danger">
          No hay resultados para pacientes "{{ query|escape }}"
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        <div class="container" id="seach_data">
          <div class="row">
            <div class="col-md-8">
              <div class="page-header"><h2>Búsquedas</h2></div>
              <form action="." method="GET" role="form">
                  {% csrf_token %}
                  <div class="form-group">
                      <div class="input-group col-md-12">
                          <input type="text" name="q" value="{{ query|escape }}"  class="form-control input-lg" placeholder="Buscar" />
                          <span class="input-group-btn">
                              <button  class="btn btn-info btn-lg" type="submit">
                                  <i class="glyphicon glyphicon-search"></i>
                              </button>
                              <a href="{% url 'paciente_alta' %}" class="btn btn-success btn-lg">
                                Agregar Paciente
                                <i class="glyphicon glyphicon-plus"></i>
                              </a>
                          </span>
                      </div>
                  </div>
              </form>
            </div>
          </div>
        </div>
      {% endif %}

    {% endif %}
  </div><hr>
{% endblock %}